language: java
jdk: oraclejdk8
services: mongodb
script: mvn exec:java -Dexec.mainClass="com.mayab.calidad.travis.JavaMongoDbDemo"
after_success: echo "I'm done"

notifications:
  email:
   - patricia.ortegon@gmail.com
  on_success: always # default: change
